server:
  port: 8085


kafka:
  producer:
    properties: /producer.properties

logging:
  level:
    .: DEBUG
    feign: DEBUG
    ru.demo.kafka: DEBUG
    org.springframework:
      web.filter.CommonsRequestLoggingFilter: DEBUG
      security: DEBUG